name: Build when create new pull request

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: docker-compose.yml

